#read data from file
data_controller_unoptimised_10 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/controller_unoptimised_10.txt")
data_controller_unoptimised_100 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/controller_unoptimised_100.txt")
data_controller_unoptimised_1000 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/controller_unoptimised_1000.txt")
data_controller_SAT_10 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/controller_SAT_10.txt")
data_controller_SAT_100 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/controller_SAT_100.txt")
data_controller_SAT_1000 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/controller_SAT_1000.txt")
data_controller_boundingSpheres_10 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/controller_boundingSpheres_10.txt")
data_controller_boundingSpheres_100 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/controller_boundingSpheres_100.txt")
data_controller_boundingSpheres_1000 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/controller_boundingSpheres_1000.txt")
data_AABB_TD_median_10 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/AABB_TD_median_10.txt")
data_AABB_TD_median_100 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/AABB_TD_median_100.txt")
data_AABB_TD_median_1000 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/AABB_TD_median_1000.txt")
data_AABB_TD_SAH_10 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/AABB_TD_SAH_10.txt")
data_AABB_TD_SAH_100 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/AABB_TD_SAH_100.txt")
data_AABB_TD_SAH_1000 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/AABB_TD_SAH_1000.txt")
data_AABB_insertion_SAH_10 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/AABB_insertion_SAH_10.txt")
data_AABB_insertion_SAH_100 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/AABB_insertion_SAH_100.txt")
data_AABB_insertion_SAH_1000 <- read.table("C:/Users/Skuta/Documents/kandidatarbete/tider/AABB_insertion_SAH_1000.txt")

#convert data to numeric matrix
library(stringr)
controller_unoptimised_10 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_controller_unoptimised_10[,1], ";",4), fixed = TRUE))),ncol = 4)
controller_unoptimised_100 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_controller_unoptimised_10[,1], ";",4), fixed = TRUE))),ncol = 4)
controller_unoptimised_1000 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_controller_unoptimised_10[,1], ";",4), fixed = TRUE))),ncol = 4)
controller_SAT_10 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_controller_SAT_10[,1], ";",4), fixed = TRUE))),ncol = 4)
controller_SAT_100 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_controller_SAT_10[,1], ";",4), fixed = TRUE))),ncol = 4)
controller_SAT_1000 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_controller_SAT_10[,1], ";",4), fixed = TRUE))),ncol = 4)
controller_boundingSpheres_10 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_controller_boundingSpheres_10[,1], ";",4), fixed = TRUE))),ncol = 4)
controller_boundingSpheres_100 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_controller_boundingSpheres_10[,1], ";",4), fixed = TRUE))),ncol = 4)
controller_boundingSpheres_1000 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_controller_boundingSpheres_10[,1], ";",4), fixed = TRUE))),ncol = 4)
AABB_TD_median_10 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_AABB_TD_median_10[,1], ";",4), fixed = TRUE))),ncol = 4)
AABB_TD_median_100 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_AABB_TD_median_100[,1], ";",4), fixed = TRUE))),ncol = 4)
AABB_TD_median_1000 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_AABB_TD_median_1000[,1], ";",4), fixed = TRUE))),ncol = 4)
AABB_TD_SAH_10 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_AABB_TD_SAH_10[,1], ";",4), fixed = TRUE))),ncol = 4)
AABB_TD_SAH_100 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_AABB_TD_SAH_100[,1], ";",4), fixed = TRUE))),ncol = 4)
AABB_TD_SAH_1000 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_AABB_TD_SAH_1000[,1], ";",4), fixed = TRUE))),ncol = 4)
AABB_insertion_SAH_10 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_AABB_insertion_SAH_10[,1], ";",4), fixed = TRUE))),ncol = 4)
AABB_insertion_SAH_100 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_AABB_insertion_SAH_100[,1], ";",4), fixed = TRUE))),ncol = 4)
AABB_insertion_SAH_1000 <- matrix(as.numeric(as.matrix(sub(",", ".",str_split_fixed(data_AABB_insertion_SAH_1000[,1], ";",4), fixed = TRUE))),ncol = 4)

#generate average_time for each column
averages_controller_unoptimised_10 = apply(controller_unoptimised_10, 2, mean)
averages_controller_unoptimised_100 = apply(controller_unoptimised_100, 2, mean)
averages_controller_unoptimised_1000 = apply(controller_unoptimised_1000, 2, mean)
averages_controller_SAT_10 = apply(controller_SAT_10, 2, mean)
averages_controller_SAT_100 = apply(controller_SAT_100, 2, mean)
averages_controller_SAT_1000 = apply(controller_SAT_1000, 2, mean)
averages_controller_boundingSpheres_10 = apply(controller_boundingSpheres_10, 2, mean)
averages_controller_boundingSpheres_100 = apply(controller_boundingSpheres_100, 2, mean)
averages_controller_boundingSpheres_1000 = apply(controller_boundingSpheres_1000, 2, mean)
averages_AABB_TD_median_10 = apply(AABB_TD_median_10, 2, mean)
averages_AABB_TD_median_100 = apply(AABB_TD_median_100, 2, mean)
averages_AABB_TD_median_1000 = apply(AABB_TD_median_1000, 2, mean)
averages_AABB_TD_SAH_10 = apply(AABB_TD_SAH_10, 2, mean)
averages_AABB_TD_SAH_100 = apply(AABB_TD_SAH_100, 2, mean)
averages_AABB_TD_SAH_1000 = apply(AABB_TD_SAH_1000, 2, mean)
averages_AABB_insertion_SAH_10 = apply(AABB_insertion_SAH_10, 2, mean)
averages_AABB_insertion_SAH_100 = apply(AABB_insertion_SAH_100, 2, mean)
averages_AABB_insertion_SAH_1000 = apply(AABB_insertion_SAH_1000, 2, mean)

#generate total_time for each row
totals_controller_unoptimised_10 = rowSums(controller_unoptimised_10)
totals_controller_unoptimised_100 = rowSums(controller_unoptimised_100)
totals_controller_unoptimised_1000 = rowSums(controller_unoptimised_1000)
totals_controller_SAT_10 = rowSums(controller_SAT_10)
totals_controller_SAT_100 = rowSums(controller_SAT_100)
totals_controller_SAT_1000 = rowSums(controller_SAT_1000)
totals_controller_boundingSpheres_10 = rowSums(controller_boundingSpheres_10)
totals_controller_boundingSpheres_100 = rowSums(controller_boundingSpheres_100)
totals_controller_boundingSpheres_1000 = rowSums(controller_boundingSpheres_1000)
totals_AABB_TD_median_10 = rowSums(AABB_TD_median_10)
totals_AABB_TD_median_100 = rowSums(AABB_TD_median_100)
totals_AABB_TD_median_1000 = rowSums(AABB_TD_median_1000)
totals_AABB_TD_SAH_10 = rowSums(AABB_TD_SAH_10)
totals_AABB_TD_SAH_100 = rowSums(AABB_TD_SAH_100)
totals_AABB_TD_SAH_1000 = rowSums(AABB_TD_SAH_1000)
totals_AABB_insertion_SAH_10 = rowSums(AABB_insertion_SAH_10)
totals_AABB_insertion_SAH_100 = rowSums(AABB_insertion_SAH_100)
totals_AABB_insertion_SAH_1000 = rowSums(AABB_insertion_SAH_1000)

#create and plot fitted lines for execution over time, in 3 graphs using n=10,100,1000
library(gcookbook)

#plot columns split into average times for each Build,CD,CH,Other for each plot, in 3 graphs using n=10,100,1000

plot(as.numeric(sub(",", ".", my_data[,1], fixed = TRUE)))